use_frameworks!

target 'VIPERS-Router_Example' do

  pod 'VIPERS-Router', :path => '../'
  pod 'VIPERS-Router-Protocol', :path => '../../VIPERS-Router-Protocol'
  #pod 'VIPERS-Converter-Protocol', :path => '../../VIPERS-Converter-Protocol'
  #pod 'VIPERS-Converter', :path => '../../VIPERS-Converter'


end


target 'VIPERS-Router_Tests' do
    
    pod 'VIPERS-Router', :path => '../'
    pod 'VIPERS-Router-Protocol', :path => '../../VIPERS-Router-Protocol'
    #pod 'VIPERS-Converter-Protocol', :path => '../../VIPERS-Converter-Protocol'
    #pod 'VIPERS-Converter', :path => '../../VIPERS-Converter'
    
end
